Add support for integrating permian into daily kikcstart tests GitHub workflow
rhinstaller/permian pull request #10
Opened 2022-03-04 10:07 UTC by rvykydal

This PR is addressing review comments from https://github.com/rhinstaller/permian/pull/4

The first four commits were open as separate PRs:
https://github.com/rhinstaller/permian/pull/6
https://github.com/rhinstaller/permian/pull/7
https://github.com/rhinstaller/permian/pull/8

2022-03-04 15:29 UTC, velezd requested changes

2022-03-04 15:29 UTC, velezd commented on libpermian/plugins/kickstart_test/__init__.py
> +        platforms = self.crcList.by_configuration('platform')
crcs with different platforms can be split to separate instances of the workflow in factory and this problem can be avoided, or am I missing something?

2022-03-07 12:54 UTC, velezd commented on libpermian/plugins/kickstart_test/__init__.py
> +@api.events.register_structure('installationUrls')
@pholica do you agree?

2022-03-08 12:16 UTC, rvykydal commented
I'll open a better PR.

2022-03-08 12:16 UTC, closed without merging